#pragma once

using namespace ATL;

template <class T>
class CProxy_IATLControlEvents : public IConnectionPointImpl<T, &__uuidof(_IATLControlEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
